batch-size: 8
check-mode: letter+word
debug: true
defaultexclude: ^(\.git|.*\.zip|.*\.gz|.*\.xz|.*\.bz2|.*\.zstd|.*\.7z|.*\.dll|.*\.iso|.*\.bin|.*\.tar|.*\.exe)$
exclude: ""
fptn: .*
group-index-a: []
group-index-b: []
path-exclude: ""
profile: ""
regexp: []
save-config: cred-detect-config.yaml
skipbinary: true
words-list-url: https://github.com/dwyl/english-words/blob/master/words.txt
